apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app # ✅ Doit correspondre au Service
    spec:
      containers:
        - name: register-app
          image: martinez42/connectocloud
          command: ["yarn", "dev", "--hostname", "0.0.0.0"]
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
