apiVersion: v1
kind: Service
metadata:
  name: register-app-service # Renommé pour cohérence
  labels:
    app: register-app
spec:
  selector:
    app: register-app # ✅ Doit correspondre au Deployment
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
