apiVersion: v1
kind: Service
metadata:
  name: connectocloud-app-service
  labels:
    app: connectocloud-app
spec:
  selector:
    app: connectocloud-app

  ports:
    - port: 3000
      targetPort: 3000

  type: ClusterIP
